### ISSUE TITLE
Particle Data mismatch

### ISSUE THREAD

**Issue by JangoBritt** [krvarma/homebridge-particle#3]
Hi @krvarma,

I am running a PietteTech_DHT code on my particle photon, and the data that is being sent to Particle is in a different format to what the plugin is looking for:

Particle reports:
`{"data":"23","ttl":"60","published_at":"2016-06-10T11:47:51.192Z","coreid":"390031001347353236343033","name":"Temperature"}`

The API call, actually reports this as:

```
event: Temperature
data: {"data":"23","ttl":"60","published_at":"2016-06-10T11:47:51.192Z","coreid":"390031001347353236343033"}
```

the plugin is expecting:

`console.log(tokens[0] + " = " + tokens[1] + ", " + this.services[1].displayName + ", " + this.sensorType + ", " + this.key.toLowerCase() + ", " + tokens[0].toLowerCase());
    console.log(this.services[1] != undefined && this.key.toLowerCase() ===`tokens[0].toLowerCase());``

So in this case, it is actually receiving the temperature in token 0, rather than in token 1.

As the data on Particle is in the key:value format, could the plugin be re-written as:

`console.log(tokens.name + " = " + tokens.data` ?

**Comment by JangoBritt** [comment]
hmm... it seems that, while tokens[1] can be swapped for tokens[0], tokens[0] cannot be swapped for tokens[5], because in the API call, the value isn't presented in the data array, only in the Event string.

I wonder if one can just use `JSON.parse(e.event)` to get the event name

**Comment by JangoBritt** [comment]
... nope

**Comment by krvarma** [comment]
@JangoBritt the data Photon publish data should be in the format "Temperature=23". Your event data has only the temperature value. The Particle Plugin expects the the event data in the format _key=value_ where key should be '_temperature_'  for temperature sensor, '_humidity_' for humidity sensor and '_light_' for light sensor. 

So in your case the sensor is a temperature sensor the data should be '_**Temperature=23**_'

Hope this will help to solve your problem.

**Comment by JangoBritt** [comment]
aaaah I see!

so I just change the code on particle to 
    Particle.publish("Temperature", "Temperature=" + String(tempc) + " °C");
    //Particle.publish("Temperature", String(tempk) + " °K");
    Particle.publish("Humidity", "Humidity=" + String(humidity) + "%");

yaaaay! That did it.

It's now parsing the Temperature into homebridge!

Might be worth adding that all-important tidbit of info into the readme.md. lol

**Comment by krvarma** [comment]
Great to know you got it working!. Keep going!

It is already included in the **readme** in the _event_name_ section. 

.... _The device firmware should publish the sensor values in the format key=value_. .....

May be it requires some more explanation. Will do it soon :)

**Comment by kebabmane** [comment]
Hi, i'm facing the same issue - my particle is publishing

        Particle.publish("Humidity", "Humidity=" + String(humidity) + "%");
        Particle.publish("Temperature", "Temperature=" + String(temperature) + " °C");

and my config looks like 

            "devices": [
                {
                    "accessory": "LivingRoomTemperature",
                    "name": "Living Room Temperature",
                    "deviceid": "DEVICEID",
                    "type": "SENSOR",
                    "sensorType": "temperature",
                    "event_name": "Temperature"
                },
                {
                    "accessory": "LivingRoomHumidity",
                    "name": "Living Room Humidity",
                    "deviceid": "DEVICEID",
                    "type": "SENSOR",
                    "sensorType": "humidity",
                    "event_name": "Humidity"
                }
            ]

however i'm receiving the same error message as above (.toLowerCase()))
